"""add status to blogpost

Revision ID: e517ca660b9c
Revises: 9b7a8ac80e88
Create Date: 2026-05-12 20:48:55.596035

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e517ca660b9c"
down_revision = "9b7a8ac80e88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create the column as nullable
    op.add_column(
        "blog_posts", sa.Column("status", sa.String(length=20), nullable=True)
    )

    # 2. SEED THE DATA: Give all existing rows a default value
    op.execute("UPDATE blog_posts SET status = 'published'")

    # 3. NOW set it to non-nullable
    op.alter_column("blog_posts", "status", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
